simple/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users', include('users.urls', namespace='users')),
    url(r'^projects', include('projects.urls', namespace='projects')),
    url(r'^', include('home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simple/home/urls.py
from django.conf.urls import url

from home.views import LandingView

urlpatterns = [
    # Landing page
    url('^$', LandingView.as_view(), name='landing'),
]

simple/projects/comments/urls.py
from django.conf.urls import url

from projects.comments.views import CommentAdd, CommentEdit, CommentDelete

urlpatterns = [
    # Create new comment
    url(
        r'^\/new',
        CommentAdd.as_view(),
        name='comment_add'
    ),

    # Edit a specific comment
    url(
        r'^\/(?P<pk>\d+)/edit$',
        CommentEdit.as_view(),
        name='comment_edit'
    ),

    # Delete a specific comment
    url(
        r'^\/(?P<pk>\d+)/delete$',
        CommentDelete.as_view(),
        name='comment_delete'
    ),
]

simple/projects/urls.py
from django.conf.urls import url, include
from views import ProjectEdit
from forms import ProjectQuestionForm
from views import revokeproject, favorite_create, favorite_delete
from .views import ProjectDetail, ProjectList, ProjectNewView,\
    ProjectApproveList, ProjectApproveView, ProjectDenyView, \
    ProjectContributeView, ProjectPendingApproval, \
    ProjectApproveContributionList, UserProjectList, \
    ProjectContributionApproveView, ProjectContributionDenyView,\
    SearchProject, UpvoteView, DownvoteView, ProjectTechnicalRequestList, \
    ProjectTechnicalRequestNewView, FavoritesView,ProjectTechnicalRequestAnswerDetail, ProjectTechnicalRequestAnswerNewView, NotificationsView

urlpatterns = [
    # Include comments application
    url(
        r'^\/(?P<project>\d+)/comments',
        include('projects.comments.urls', namespace='comments')
    ),

    # Include activities application
    url(
       r'^\/(?P<project>\d+)/activities',
       include('projects.activities.urls', namespace='activities')
    ),

    # List of Projects
    url(
        r'^$',
        ProjectList.as_view(),
        name='list'
    ),

    # List of Projects by User
    url(
        r'^\/user/(?P<user>\d+)$',
        UserProjectList.as_view(),
        name='user-list'
    ),


    # Project details
    url(
        r'^\/(?P<pk>\d+)$',
        ProjectDetail.as_view(),
        name='detail'
    ),

    # New project
    url(
        r'^\/new$',
        ProjectNewView.as_view(),
        name='new'
    ),

    # Search Project
    url(
        r'^\/search/(?P<title>.*)/$',
        SearchProject.as_view(),
        name='search-project'
    ),

    # Pending approval message view shown after project creation
    url(
        r'^\/pending-approval',
        ProjectPendingApproval.as_view(),
        name='pending-approval'
    ),

    # Approve / deny projects list
    url(
        r'^\/approve$',
        ProjectApproveList.as_view(),
        name='approve-list'
    ),

    # Approve project
    url(
        r'^\/approve/(?P<pk>\d+)$',
        ProjectApproveView.as_view(),
        name='approve-project'
    ),

    # Deny project
    url(
        r'^\/deny/(?P<pk>\d+)$',
        ProjectDenyView.as_view(),
        name='deny-project'
    ),

    # Contribute to project
    url(
        r'\/(?P<pk>\d+)/contribute$',
        ProjectContributeView.as_view(),
        name='contribute'
    ),

    # Approve / deny contribution list
    url(
        r'\/approve-contributions$',
        ProjectApproveContributionList.as_view(),
        name='approve-contributions-list'
    ),

    # Approve contribution
    url(
        r'\/approve-contribution/project/(?P<pk>\d+)/user/(?P<user>\d+)/$',
        ProjectContributionApproveView.as_view(),
        name='approve-contribution'
    ),

    # Deny contribution
    url(
        r'\/deny-contribution/project/(?P<pk>\d+)/user/(?P<user>\d+)$',
        ProjectContributionDenyView.as_view(),
        name='deny-contribution'
    ),

    # Edit Project
    url(
        r'^\/(?P<pk>\d+)/edit$',
        ProjectEdit.as_view(),
        name='edit'
    ),

    # Technical Requests list
    url(
        r'^\/(?P<project>\d+)/technical-requests$',
        ProjectTechnicalRequestList.as_view(),
        name='technical-requests'
    ),

    # Add Technical Request
    url(
        r'^\/(?P<project>\d+)/technical-requests/new$',
        ProjectTechnicalRequestNewView.as_view(),
        name='technical-request-new'
    ),

    # See Technical Request Answer
    url(
        r'^\/(?P<project>\d+)/technical-requests/(?P<pk>\d+)$',
        ProjectTechnicalRequestAnswerDetail.as_view(),
        name='technical-request-answer'
    ),

    # Reply Technical Request
    url(
        r'^\/(?P<project>\d+)/technical-requests/(?P<pk>\d+)/reply',
        ProjectTechnicalRequestAnswerNewView.as_view(),
        name='technical-request-answer-new'
    ),


    # Vote up project
    url(
        r'^\/(?P<pk>\d+)/vote/up$',
        UpvoteView.as_view(),
        name='upvote'
    ),

    # Vote down project
    url(
        r'^\/(?P<pk>\d+)/vote/down$',
        DownvoteView.as_view(),
        name='downvote'
    ),

    # Favorites projects
    url(
        r'^\/favorites$',
        FavoritesView.as_view(),
        name='favorites'
    ),

    # New favorite
    url(
        r'^\/favorites/create$',
        favorite_create,
        name='favorite_create'
    ),

    # Delete favorite
    url(
        r'^\/favorites/delete$',
        favorite_delete,
        name='favorite_delete'
    ),

    url(
        r'^\/(?P<pk>\d+)/notifications$',
        NotificationsView.as_view(),
        name='notifications'
    ),
    # Revoke in a project
    url(r'\/contribute/delete$',
        revokeproject,
        name='revoke'
        )

]

simple/users/urls.py
from django.conf.urls import url

from .views import RegisterView, LoginView, AccountView, UserList, SearchUser, \
    LogoutView, UserEditView

urlpatterns = [
    # login
    url(
        r'^\/login$',
        LoginView.as_view(),
        name='login'
    ),

    # logout
    url(
        r'^\/logout$',
        LogoutView.as_view(),
        name='logout'
    ),

    # sign up
    url(
        r'^\/signup$',
        RegisterView.as_view(),
        name='signup'
    ),

    # user account
    url(
        r'^\/(?P<pk>\d+)$',
        AccountView.as_view(),
        name='account'
    ),

    # user list
    url(
        r'^$',
        UserList.as_view(),
        name='list'
    ),

    # search user
    url(
        r'^\/search/(?P<first_name>.*)/$',
        SearchUser.as_view(),
        name='search-user'
    ),

    # edit user
    url(
        r'^\/(?P<pk>\d+)/edit$',
       UserEditView.as_view(),

        name='edit-user'
    ),


]

simple/projects/activities/models.py
from .abstract_models import AbstractProjectActivity, \
    AbstractProjectActivityResponse, AbstractProjectActivityAttachment, \
    AbstractProjectActivityResponseAttachment


class ProjectActivity(AbstractProjectActivity):
    pass


class ProjectActivityAttachment(AbstractProjectActivityAttachment):
    pass


class ProjectActivityResponse(AbstractProjectActivityResponse):
    pass


class ProjectActivityResponseAttachment(AbstractProjectActivityResponseAttachment):
    pass

simple/projects/comments/models.py
from __future__ import unicode_literals

from .abstract_models import AbstractComment, AbstractCommentAttachment


class Comment(AbstractComment):
    pass


class CommentAttachment(AbstractCommentAttachment):
    pass

simple/projects/activities/forms.py
from datetimewidget.widgets import DateTimeWidget
from django import forms
from multiupload.fields import MultiFileField

from config.constants import MediaFile
from .models import ProjectActivity, ProjectActivityResponse


class ActivityNewForm(forms.ModelForm):
    """
    Form for creating a new Activity
    """
    attachments = MultiFileField(required=False, min_num=1,
                                 max_num=MediaFile.PROJECT_ATTACHMENT_MULTIUPLOAD,
                                 max_file_size=MediaFile.PROJECT_ATTACHMENT.max_size)

    class Meta:
        model = ProjectActivity
        fields = ('title', 'body', 'start_date', 'due_date')
        widgets = {
            'body': forms.Textarea(attrs={'placeholder': u'Activity description'}),
            'start_date': DateTimeWidget(),
            'due_date': DateTimeWidget(),
        }


class ActivityResponseNewForm(forms.ModelForm):
    """
    Form for replying to an Activity
    """
    attachments = MultiFileField(required=False, min_num=1,
                                 max_num=MediaFile.PROJECT_ATTACHMENT_MULTIUPLOAD,
                                 max_file_size=MediaFile.PROJECT_ATTACHMENT.max_size)

    class Meta:
        model = ProjectActivityResponse
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'placeholder': u'Response description'})
        }

simple/projects/comments/forms.py
from django import forms
from multiupload.fields import MultiFileField

from config.constants import MediaFile
from .models import Comment


class CommentAddForm(forms.ModelForm):
    """
    A form for creating comments.
    """
    attachments = MultiFileField(required=False, min_num=1,
                                 max_num=MediaFile.PROJECT_ATTACHMENT_MULTIUPLOAD,
                                 max_file_size=MediaFile.PROJECT_ATTACHMENT.max_size)

    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(
                attrs={'placeholder': u'Comment description'}),
        }


class CommentEditForm(forms.ModelForm):
    """
    A form for editing comments.
    """
    attachments = MultiFileField(required=False, min_num=1,
                                 max_num=MediaFile.PROJECT_ATTACHMENT_MULTIUPLOAD,
                                 max_file_size=MediaFile.PROJECT_ATTACHMENT.max_size)

    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(
                attrs={'placeholder': u'Content description'}),
        }

simple/projects/activities/views.py
from annoying.functions import get_object_or_None
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

from projects.activities.forms import ActivityNewForm, ActivityResponseNewForm
from projects.activities.mixins import ActivityOpenMixin, ActivityBaseMixin
from projects.mixins import ScientistOrStudentRequiredMixin, \
    ScientistRequiredMixin, StudentRequiredMixin
from projects.models import Project, ProjectRole
from .models import ProjectActivity, ProjectActivityResponse, \
    ProjectActivityAttachment, ProjectActivityResponseAttachment


class ActivityList(ScientistOrStudentRequiredMixin,
                   ActivityBaseMixin, ListView):
    template_name = 'projects/activities/list.html'
    model = ProjectActivity
    context_object_name = 'activities'
    ordering = ['-created']

    def get_queryset(self):
        project = get_object_or_404(Project, id=self.kwargs['project'])
        queryset = self.model.objects.filter(project=project)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ActivityList, self).get_context_data()
        context['project'] = get_object_or_404(Project, id=self.kwargs['project'])
        context['user_project_role'] = get_object_or_404(ProjectRole,
                                                         project=context['project'],
                                                         user=self.request.user)
        return context


class ActivityNewView(ScientistRequiredMixin, ActivityBaseMixin, CreateView):
    template_name = 'projects/activities/new.html'
    model = ProjectActivity
    form_class = ActivityNewForm

    def form_valid(self, form):
        activity = form.save(commit=False)
        activity.user = self.request.user
        activity.project = get_object_or_404(Project, id=self.kwargs['project'])
        activity.save()

        # save attachments
        for each in form.cleaned_data['attachments']:
            ProjectActivityAttachment.objects.create(activity=activity,
                                                     object=each)

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('projects:activities:list', args=[self.kwargs['project']])

    def get_context_data(self, **kwargs):
        context = super(ActivityNewView, self).get_context_data()
        context['project'] = get_object_or_404(Project, id=self.kwargs['project'])
        return context


class ActivityDetailView(ScientistOrStudentRequiredMixin,
                         ActivityBaseMixin, DetailView):
    template_name = 'projects/activities/detail.html'
    model = ProjectActivity
    context_object_name = 'activity'

    def get_context_data(self, **kwargs):
        context = super(ActivityDetailView, self).get_context_data()
        context['project'] = get_object_or_404(Project, id=self.kwargs['project'])
        context['activity_responses'] = context['activity']\
            .projectactivityresponse_set.all()
        context['user_activity_responses'] = context['activity']\
            .projectactivityresponse_set.filter(user=self.request.user)
        return context

#
# ACTIVITY REPLIES
#


class ActivityResponseNewView(StudentRequiredMixin, ActivityBaseMixin,
                              ActivityOpenMixin, CreateView):
    template_name = "projects/activities/response-new.html"
    model = ProjectActivityResponse
    form_class = ActivityResponseNewForm

    def form_valid(self, form):
        response = form.save(commit=False)
        response.user = self.request.user
        response.project = get_object_or_404(Project, id=self.kwargs['project'])
        response.activity = get_object_or_404(ProjectActivity,
                                              id=self.kwargs['activity'])
        response.save()

        # save attachments
        for each in form.cleaned_data['attachments']:
            ProjectActivityResponseAttachment.objects.create(response=response, object=each)

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('projects:activities:list',
                       args=[self.kwargs['project']])

    def get_context_data(self, **kwargs):
        context = super(ActivityResponseNewView, self).get_context_data(**kwargs)
        context['project'] = get_object_or_404(Project, id=self.kwargs['project'])
        context['activity'] = get_object_or_404(ProjectActivity,
                                                id=self.kwargs['activity'])
        context['activity_response'] = \
            get_object_or_None(ProjectActivityResponse,
                               user=self.request.user,
                               activity=self.kwargs['project'])
        return context

simple/projects/comments/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView

from core.mixins import OwnerRequiredMixin
from core.utils import WordFilter
from projects.models import Project
from .models import Comment, CommentAttachment
from .forms import CommentAddForm, CommentEditForm
from .mixins import CommentEditMixin, CommentDeleteMixin, CommentBaseMixin


class CommentAdd(OwnerRequiredMixin, CommentBaseMixin, CreateView):
    template_name = 'projects/comments/comment_add.html'
    model = Comment
    form_class = CommentAddForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.user = self.request.user
        comment.project = get_object_or_404(Project, id=self.kwargs['project'])
        comment.content = WordFilter().clean(form.instance.content)
        comment.save()

        # save attachments
        for each in form.cleaned_data['attachments']:
            CommentAttachment.objects.create(comment=comment,
                                             object=each)

        self.object = comment
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('projects:detail', args=[self.kwargs['project']]) + \
               '#comment_' + str(self.object.id)


class CommentEdit(CommentEditMixin):
    template_name = 'projects/comments/comment_edit.html'
    form_class = CommentEditForm

    def form_valid(self, form):
        # word filters
        form.instance.content = WordFilter().clean(form.instance.content)

        # save attachments
        for each in form.cleaned_data['attachments']:
            CommentAttachment.objects.create(comment=form.instance, object=each)

        return super(CommentEdit, self).form_valid(form)

    def get_success_url(self):
        return reverse('projects:detail', args=[self.kwargs['project']]) + \
               '#comment_' + str(self.object.id)


class CommentDelete(CommentDeleteMixin):
    template_name = 'projects/comments/comment_delete.html'

    def get_success_url(self):
        return reverse('projects:detail', args=[self.kwargs['project']]) + \
               '#comment_' + str(self.object.id)

simple/templates/projects/approve-contribution-list.html
{% extends "projects/base.html" %}
{% load breadcrumb %}

{% block breadcrumb_ %}
    {{ block.super }}
    {% breadcrumb_url "Approve contribution petitions" "projects:approve-contributions-list" %}
{% endblock %}

{% block menu_title %}
    <h1>Approve contribution petitions</h1>
{% endblock %}

{% block app_content %}
    {% regroup projectroles by project as projects %}
    <div class="center page-width">
        <ul>
            {% for project in projects %}
                <h2>
                    <a href="{% url "projects:detail" project.grouper.id %}" target="_blank">
                        {{ project.grouper | truncatechars:50 }}
                        <i class="fa fa-external-link fa-1" aria-hidden="true" style="font-size:16px;"></i>
                    </a>
                </h2>

                {% for role in project.list %}
                    <div class="box">
                        <ul class="enumerateless">
                            <li>
                                {{ role.user }}
                                {{ role.get_role_str }}
                                <a href="{% url "projects:approve-contribution" role.project.id role.user.id %}">Approve</a>
                                <a href="{% url "projects:deny-contribution" role.project.id role.user.id %}">Deny</a>
                            </li>
                        </ul>
                    </div>
                {% endfor %}
            {% empty %}
                <div class="center-text">
                    Job's done!
                </div>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

simple/templates/projects/approve-list.html
{% extends "projects/base.html" %}
{% load breadcrumb %}

{% block breadcrumb_ %}
    {{ block.super }}
    {% breadcrumb_url "Approve project proposals" "projects:approve-list" %}
{% endblock %}

{% block menu_title %}
    <h1>Approve project proposals</h1>
{% endblock %}

{% block app_content %}
    <div class="center page-width">
        {% for project in projects %}
            <div class="box">
                <ul class="enumerateless">
                    <li>
                        {{ project.title }}
                        <a href="{% url "projects:approve-project" project.id %}">Approve</a>
                        <a href="{% url "projects:deny-project" project.id %}">Deny</a>
                    </li>
                </ul>
            </div>
        {% empty %}
            <div class="center-text">
                Job's done!
            </div>
        {% endfor %}
    </div>
{% endblock %}

simple/templates/projects/detail.html
{% extends "projects/base.html" %}
{% load static %}

{% block local_scripts %}
<script src="{% static "js/projects/vote.js" %}"></script>
{% endblock %}

{% block menu %}
{% endblock %}

{% block breadcrumb %}
    {# exception: breadcrumb exempt #}
{% endblock %}

{% block app_content %}
    <div class="project-detail container-fluid">
        <input type="hidden" id="project_id" value="{{ project.id }}" />
        <div class="project-detail-header row">
            <div class="project-image col-xs-6"
                 style="background-image: url({{ MEDIA_URL }}{{ project.picture }})">
                {# project image as bg #}
            </div>
            <div class="project-info col-xs-6">
                <div class="container-fluid">
                    <div class="row">
                        <form method="post" action="{% url 'projects:favorite_create' %}" style="float: right">
                            {% csrf_token %}
                            <input name="project" type="hidden" value="{{ project.id }}" />
                            <button type="submit" class="btn btn-warning"><span class="glyphicon glyphicon-star-empty"></span> Add Favorite</button>
                        </form>
                      <h1>{{ project.title }}</h1>
                    </div>
                    <div class = "row">
                        <i><a href="{{ MEDIA_URL }}{{project.picture }}"
                        onclick="window.open(this.href,'resizable=yes,location=yes,toolbar=no,status=no,fullscreen=yes,dependent=no,status');
                        return false"><span class="glyphicon glyphicon-zoom-in"></span></a></i>
                    </div>
                    <div class="row">
                        <i>Last modified: {{ project.modified }}</i>
                    </div>
                    <div class="row">
                        <i>Created: {{ project.created }}</i>
                    </div>
                    <div class="row">
                        <i>Author: <a href="{% url "users:account" project.user.id %}">{{ project.user.get_short_name }}</a></i>
                    </div>
                    <div class="row">
                        <i>Views: {{ project.visits }}</i>
                    </div>
                    <div class="tools">
                        {% if request.user.is_staff or user_project_role.role == PROJECT_ROLES.SCIENTIST %}
                            <a href="{% url "projects:edit" project.id %}">
                                Edit
                            </a>
                        {% endif %}
                        <a href="#">Members</a>
                        <a href="#">Contributors</a>
                        <a href="{% url "projects:technical-requests" project.id %}">Technical requests</a>
                        <a href="{% url "projects:contribute" project.id %}">Request membership</a>
                        {% if request.user.is_staff or user_project_role.role == PROJECT_ROLES.SCIENTIST or user_project_role.role == PROJECT_ROLES.STUDENT %}
                            <a href="{% url "projects:activities:list" project.id %}">Activities</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="page-detail-stats row">
            <div class="page-detail-stats-inner">
                <div class="likes">
                    <div class="like">
                        {% if user_project_rating and user_project_rating.is_upvoted %}
                            <i class="like-btn fa fa-thumbs-up fa-3 selected"></i>
                        {% else %}
                            <i class="like-btn fa fa-thumbs-up fa-3"></i>
                        {% endif %}
                        <span class="likes-res">{{ project.upvotes }}</span>
                    </div>
                    <div class="dislike">
                        {% if user_project_rating and user_project_rating.rating.is_downvoted %}
                            <i class="dislike-btn fa fa-thumbs-down fa-2 selected"></i>
                        {% else %}
                            <i class="dislike-btn fa fa-thumbs-down fa-2"></i>
                        {% endif %}
                        <span class="dislikes-res">{{ project.downvotes }}</span>
                    </div>
                </div>
            </div>
        </div>

        <div class="page-detail-description">
            {{ project.body }}
        </div>

        <div class="page-detail-attachments">
            {% include "attachments.html" with attachments=project.attachments.all %}
        </div>

        <div class="page-detail-comments">
            <h2>Comments</h2>
            <a href = "{% url 'projects:comments:comment_add' project.id %}">New Comment</a>
            {% for comment in object.comments.all %}
                <div id="comment_{{ comment.id }}">
                    <div>
                        User: {{ comment.user.first_name }}
                        {% if comment.user == request.user %}
                            <a href = "{% url 'projects:comments:comment_edit' project.id comment.id %}">Edit</a>
                        {% endif %}

                        {% if comment.user == request.user or request.user.role == USER_ROLES.MODERATOR %}
                            <a href = "{% url 'projects:comments:comment_delete' project.id comment.id %}">Delete</a>
                        {% endif %}
                    <div>
                        Published: {{ comment.created }}
                        Modified: {{ comment.modified }}
                    </div>
                    </div>
                    <div>
                        {% if comment.is_removed %}
                            <i>Removed</i>
                        {% else %}
                            {{ comment.content }}
                            {% include "attachments.html" with attachments=comment.comment_attachments.all %}
                        {% endif %}
                    </div>
                </div>
                <hr>
            {% empty %}
                No comments - be the first one to post!
            {% endfor %}
        </div>
    </div>
{% endblock %}

simple/templates/projects/favorites.html
{% extends "projects/base.html" %}
{% load breadcrumb %}

{% block breadcrumb_ %}
    {{ block.super }}
    {% breadcrumb_url "New favorite" "projects:favorite_create" %}
{% endblock %}

{% block menu_title %}
    <h1>New favorite</h1>
{% endblock %}

{% block app_content %}
    <script type="text/javascript">
        function search(event, project) {
            if (event.which == 13 || event.keyCode == 13){
                location.href= '/projects/search/' + project;
            }
        }
    </script>

    <div class="center box" style="width:800px">
        {% if added %}
            <strong>Success!</strong> Project {{ project }}has been added <a href="/projects/favorites">Back</a>
        {% elif exist %}
             <strong>Error!</strong> Project {{ project }} already exists in your Favorites. <a href="/projects/favorites">Back</a>
        {% else %}
            {% for project in favorites %}
            {% if project.project.approved %}
                <div class='alert alert-info alert-dismissible' role='alert'>
                <img src="{{ MEDIA_URL }}{{ project.project.picture }}" style="height:70px;margin-right:35px;float:left;" />
                    <div class="project-title">
                    {{ project.project.title }}
                    </div>
                    <div class="project-body">
                        <div class="project-description">
                            {{ project.body | truncatechars:150 }}
                        </div>
                        <div class="project-author">
                            Started by {{ project.user.get_short_name }}
                        </div>
                        <div class="project-buttons">
                            <a href="{% url "projects:detail" project.id %}">
                                Explore
                            </a>
                            {% if project.user == request.user %}
                                <a href = "{% url "projects:edit" project.id %}">Edit</a>
                            {% endif %}
                        </div>

                    </div>
                 <form action="{% url 'projects:favorite_delete' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="project" value="{{ project.project.id }}">
                        <button type="button" type="submit" class="btn btn-danger" style="float: right;margin-top:-50px;">Delete</button>
                 </form>
                </div>
            {% endif %}
                {% empty %}
                    <div class='alert alert-info alert-dismissible error-search'  role= 'alert'>
                        <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hideen='true'>&times;</span></button>
                        <strong>No results</strong> Your search returned no matches.
                    </div>
            {% endfor %}
        {% endif %}
    </div>

{% endblock %}

simple/templates/projects/pending-approval.html
{% extends "projects/base.html" %}
{% load breadcrumb %}

{% block breadcrumb_ %}
    {{ block.super }}
    {% breadcrumb_url "New project" "projects:new" %}
{% endblock %}

{% block menu_title %}
<h1>New Project</h1>
{% endblock %}

{% block app_content %}
    <div class="center center-text">
        {% for message in messages %}
            <p>Your project <b>{{ message }}</b> is now pending approval.</p>
        {% endfor %}
        <p>
            <a href="{% url "projects:list" %}">Go back to projects</a>
        </p>
    </div>
{% endblock %}

simple/templates/projects/technical-requests.html
{% extends "projects/base.html" %}
{% load breadcrumb %}

{% block breadcrumb_ %}
    {{ block.super }}
    {% with "Project '"|add:project.title|add:"'" as project_name %}
        {% breadcrumb_url project_name "projects:detail" project.id %}
    {% endwith %}
    {% breadcrumb_url "Technical requests" "projects:technical-requests" project.id %}
{% endblock %}

{% block menu_title %}
    <h1>Technical requests</h1>
{% endblock %}

{% block app_content %}
    <div class="center box" style="width:800px">
        <a class="corner-btn" href="{% url "projects:technical-request-new" project.id %}">+</a>

        {% for question in questions %}
                <div>
                    From: {{ question.from_user.first_name }}
                    To:   {{ question.to_user.first_name }}
                </div>
                <div>
                     Question: {{ question.question }}
                </div>
                <div>
                    Published: {{ question.created }}
                </div>
                <div>
                    <a href="{% url "projects:technical-request-answer" project.id question.id %}">View</a>
                    {% if question.answer %}
                        (answered)
                    {% endif %}
                </div>
            <hr>
        {% empty %}
            No questions
        {% endfor %}
    </div>
{% endblock %}