simple/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users', include('users.urls', namespace='users')),
    url(r'^projects', include('projects.urls', namespace='projects')),
    url(r'^', include('home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simple/home/urls.py
from django.conf.urls import url

from home.views import LandingView

urlpatterns = [
    # Landing page
    url('^$', LandingView.as_view(), name='landing'),
]

simple/projects/urls.py
from django.conf.urls import url, include
from views import ProjectEdit
from forms import ProjectQuestionForm
from views import revokeproject, favorite_create, favorite_delete
from .views import ProjectDetail, ProjectList, ProjectNewView,\
    ProjectApproveList, ProjectApproveView, ProjectDenyView, \
    ProjectContributeView, ProjectPendingApproval, \
    ProjectApproveContributionList, UserProjectList, \
    ProjectContributionApproveView, ProjectContributionDenyView,\
    SearchProject, UpvoteView, DownvoteView, ProjectTechnicalRequestList, \
    ProjectTechnicalRequestNewView, FavoritesView,ProjectTechnicalRequestAnswerDetail, ProjectTechnicalRequestAnswerNewView, NotificationsView

urlpatterns = [
    # Include comments application
    url(
        r'^\/(?P<project>\d+)/comments',
        include('projects.comments.urls', namespace='comments')
    ),

    # Include activities application
    url(
       r'^\/(?P<project>\d+)/activities',
       include('projects.activities.urls', namespace='activities')
    ),

    # List of Projects
    url(
        r'^$',
        ProjectList.as_view(),
        name='list'
    ),

    # List of Projects by User
    url(
        r'^\/user/(?P<user>\d+)$',
        UserProjectList.as_view(),
        name='user-list'
    ),


    # Project details
    url(
        r'^\/(?P<pk>\d+)$',
        ProjectDetail.as_view(),
        name='detail'
    ),

    # New project
    url(
        r'^\/new$',
        ProjectNewView.as_view(),
        name='new'
    ),

    # Search Project
    url(
        r'^\/search/(?P<title>.*)/$',
        SearchProject.as_view(),
        name='search-project'
    ),

    # Pending approval message view shown after project creation
    url(
        r'^\/pending-approval',
        ProjectPendingApproval.as_view(),
        name='pending-approval'
    ),

    # Approve / deny projects list
    url(
        r'^\/approve$',
        ProjectApproveList.as_view(),
        name='approve-list'
    ),

    # Approve project
    url(
        r'^\/approve/(?P<pk>\d+)$',
        ProjectApproveView.as_view(),
        name='approve-project'
    ),

    # Deny project
    url(
        r'^\/deny/(?P<pk>\d+)$',
        ProjectDenyView.as_view(),
        name='deny-project'
    ),

    # Contribute to project
    url(
        r'\/(?P<pk>\d+)/contribute$',
        ProjectContributeView.as_view(),
        name='contribute'
    ),

    # Approve / deny contribution list
    url(
        r'\/approve-contributions$',
        ProjectApproveContributionList.as_view(),
        name='approve-contributions-list'
    ),

    # Approve contribution
    url(
        r'\/approve-contribution/project/(?P<pk>\d+)/user/(?P<user>\d+)/$',
        ProjectContributionApproveView.as_view(),
        name='approve-contribution'
    ),

    # Deny contribution
    url(
        r'\/deny-contribution/project/(?P<pk>\d+)/user/(?P<user>\d+)$',
        ProjectContributionDenyView.as_view(),
        name='deny-contribution'
    ),

    # Edit Project
    url(
        r'^\/(?P<pk>\d+)/edit$',
        ProjectEdit.as_view(),
        name='edit'
    ),

    # Technical Requests list
    url(
        r'^\/(?P<project>\d+)/technical-requests$',
        ProjectTechnicalRequestList.as_view(),
        name='technical-requests'
    ),

    # Add Technical Request
    url(
        r'^\/(?P<project>\d+)/technical-requests/new$',
        ProjectTechnicalRequestNewView.as_view(),
        name='technical-request-new'
    ),

    # See Technical Request Answer
    url(
        r'^\/(?P<project>\d+)/technical-requests/(?P<pk>\d+)$',
        ProjectTechnicalRequestAnswerDetail.as_view(),
        name='technical-request-answer'
    ),

    # Reply Technical Request
    url(
        r'^\/(?P<project>\d+)/technical-requests/(?P<pk>\d+)/reply',
        ProjectTechnicalRequestAnswerNewView.as_view(),
        name='technical-request-answer-new'
    ),


    # Vote up project
    url(
        r'^\/(?P<pk>\d+)/vote/up$',
        UpvoteView.as_view(),
        name='upvote'
    ),

    # Vote down project
    url(
        r'^\/(?P<pk>\d+)/vote/down$',
        DownvoteView.as_view(),
        name='downvote'
    ),

    # Favorites projects
    url(
        r'^\/favorites$',
        FavoritesView.as_view(),
        name='favorites'
    ),

    # New favorite
    url(
        r'^\/favorites/create$',
        favorite_create,
        name='favorite_create'
    ),

    # Delete favorite
    url(
        r'^\/favorites/delete$',
        favorite_delete,
        name='favorite_delete'
    ),

    url(
        r'^\/(?P<pk>\d+)/notifications$',
        NotificationsView.as_view(),
        name='notifications'
    ),
    # Revoke in a project
    url(r'\/contribute/delete$',
        revokeproject,
        name='revoke'
        )

]

simple/users/urls.py
from django.conf.urls import url

from .views import RegisterView, LoginView, AccountView, UserList, SearchUser, \
    LogoutView, UserEditView

urlpatterns = [
    # login
    url(
        r'^\/login$',
        LoginView.as_view(),
        name='login'
    ),

    # logout
    url(
        r'^\/logout$',
        LogoutView.as_view(),
        name='logout'
    ),

    # sign up
    url(
        r'^\/signup$',
        RegisterView.as_view(),
        name='signup'
    ),

    # user account
    url(
        r'^\/(?P<pk>\d+)$',
        AccountView.as_view(),
        name='account'
    ),

    # user list
    url(
        r'^$',
        UserList.as_view(),
        name='list'
    ),

    # search user
    url(
        r'^\/search/(?P<first_name>.*)/$',
        SearchUser.as_view(),
        name='search-user'
    ),

    # edit user
    url(
        r'^\/(?P<pk>\d+)/edit$',
       UserEditView.as_view(),

        name='edit-user'
    ),


]

simple/home/views.py
from django.views.generic import TemplateView


class LandingView(TemplateView):
    template_name = 'home/landing.html'

simple/templates/home/base.html
{% extends "base.html" %}

{% block content %}
    {% block app_content %}
    {% endblock %}
{% endblock %}

simple/templates/home/landing.html
{% extends "home/base.html" %}
{% load static %}

{% block header %}
    <header id="landing-header">
        <a id="logo" href="{% url "home:landing" %}">{{ PROJECT_NAME }}</a>

        {# default header nav #}
        <div id="header-nav">
            {% include "header-nav.html" %}
        </div>

    </header>
{% endblock %}

{% block menu %}
    {# landing page has no menu #}
{% endblock %}

{% block app_content %}
    <div id="landing-body">
        <div id="landing-carousel" class="carousel slide" data-ride="carousel" data-interval="5000">
            <ol class="carousel-indicators">
                 <li data-target="#landing-carousel" data-slide-to="0" class="active"></li>
                 <li data-target="#landing-carousel" data-slide-to="1" class=""></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active" style="background: linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)), url({% static "img/landing/landing-1.jpg" %})">
                    <!-- item 1 -->
                    <div class="full-center item-description">
                        <h1>Let's work together</h1>
                        <h2>Start your project</h2>
                        <a class="item-go" href="{% url "projects:new" %}">Start</a>
                    </div>
                </div>
                <div class="item" style="background: linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)), url({% static "img/landing/landing-2.jpg" %})">
                    <!-- item 2 -->
                    <div class="full-center item-description">
                        <h1>Community projects</h1>
                        <h2>View projects</h2>
                        <a class="item-go" href="{% url "projects:list" %}">View</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    {# footer exempt #}
{% endblock %}