simple/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users', include('users.urls', namespace='users')),
    url(r'^projects', include('projects.urls', namespace='projects')),
    url(r'^', include('home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simple/home/urls.py
from django.conf.urls import url

from home.views import LandingView

urlpatterns = [
    # Landing page
    url('^$', LandingView.as_view(), name='landing'),
]

simple/projects/urls.py
from django.conf.urls import url, include
from views import ProjectEdit
from forms import ProjectQuestionForm
from views import revokeproject, favorite_create, favorite_delete
from .views import ProjectDetail, ProjectList, ProjectNewView,\
    ProjectApproveList, ProjectApproveView, ProjectDenyView, \
    ProjectContributeView, ProjectPendingApproval, \
    ProjectApproveContributionList, UserProjectList, \
    ProjectContributionApproveView, ProjectContributionDenyView,\
    SearchProject, UpvoteView, DownvoteView, ProjectTechnicalRequestList, \
    ProjectTechnicalRequestNewView, FavoritesView,ProjectTechnicalRequestAnswerDetail, ProjectTechnicalRequestAnswerNewView, NotificationsView

urlpatterns = [
    # Include comments application
    url(
        r'^\/(?P<project>\d+)/comments',
        include('projects.comments.urls', namespace='comments')
    ),

    # Include activities application
    url(
       r'^\/(?P<project>\d+)/activities',
       include('projects.activities.urls', namespace='activities')
    ),

    # List of Projects
    url(
        r'^$',
        ProjectList.as_view(),
        name='list'
    ),

    # List of Projects by User
    url(
        r'^\/user/(?P<user>\d+)$',
        UserProjectList.as_view(),
        name='user-list'
    ),


    # Project details
    url(
        r'^\/(?P<pk>\d+)$',
        ProjectDetail.as_view(),
        name='detail'
    ),

    # New project
    url(
        r'^\/new$',
        ProjectNewView.as_view(),
        name='new'
    ),

    # Search Project
    url(
        r'^\/search/(?P<title>.*)/$',
        SearchProject.as_view(),
        name='search-project'
    ),

    # Pending approval message view shown after project creation
    url(
        r'^\/pending-approval',
        ProjectPendingApproval.as_view(),
        name='pending-approval'
    ),

    # Approve / deny projects list
    url(
        r'^\/approve$',
        ProjectApproveList.as_view(),
        name='approve-list'
    ),

    # Approve project
    url(
        r'^\/approve/(?P<pk>\d+)$',
        ProjectApproveView.as_view(),
        name='approve-project'
    ),

    # Deny project
    url(
        r'^\/deny/(?P<pk>\d+)$',
        ProjectDenyView.as_view(),
        name='deny-project'
    ),

    # Contribute to project
    url(
        r'\/(?P<pk>\d+)/contribute$',
        ProjectContributeView.as_view(),
        name='contribute'
    ),

    # Approve / deny contribution list
    url(
        r'\/approve-contributions$',
        ProjectApproveContributionList.as_view(),
        name='approve-contributions-list'
    ),

    # Approve contribution
    url(
        r'\/approve-contribution/project/(?P<pk>\d+)/user/(?P<user>\d+)/$',
        ProjectContributionApproveView.as_view(),
        name='approve-contribution'
    ),

    # Deny contribution
    url(
        r'\/deny-contribution/project/(?P<pk>\d+)/user/(?P<user>\d+)$',
        ProjectContributionDenyView.as_view(),
        name='deny-contribution'
    ),

    # Edit Project
    url(
        r'^\/(?P<pk>\d+)/edit$',
        ProjectEdit.as_view(),
        name='edit'
    ),

    # Technical Requests list
    url(
        r'^\/(?P<project>\d+)/technical-requests$',
        ProjectTechnicalRequestList.as_view(),
        name='technical-requests'
    ),

    # Add Technical Request
    url(
        r'^\/(?P<project>\d+)/technical-requests/new$',
        ProjectTechnicalRequestNewView.as_view(),
        name='technical-request-new'
    ),

    # See Technical Request Answer
    url(
        r'^\/(?P<project>\d+)/technical-requests/(?P<pk>\d+)$',
        ProjectTechnicalRequestAnswerDetail.as_view(),
        name='technical-request-answer'
    ),

    # Reply Technical Request
    url(
        r'^\/(?P<project>\d+)/technical-requests/(?P<pk>\d+)/reply',
        ProjectTechnicalRequestAnswerNewView.as_view(),
        name='technical-request-answer-new'
    ),


    # Vote up project
    url(
        r'^\/(?P<pk>\d+)/vote/up$',
        UpvoteView.as_view(),
        name='upvote'
    ),

    # Vote down project
    url(
        r'^\/(?P<pk>\d+)/vote/down$',
        DownvoteView.as_view(),
        name='downvote'
    ),

    # Favorites projects
    url(
        r'^\/favorites$',
        FavoritesView.as_view(),
        name='favorites'
    ),

    # New favorite
    url(
        r'^\/favorites/create$',
        favorite_create,
        name='favorite_create'
    ),

    # Delete favorite
    url(
        r'^\/favorites/delete$',
        favorite_delete,
        name='favorite_delete'
    ),

    url(
        r'^\/(?P<pk>\d+)/notifications$',
        NotificationsView.as_view(),
        name='notifications'
    ),
    # Revoke in a project
    url(r'\/contribute/delete$',
        revokeproject,
        name='revoke'
        )

]

simple/users/urls.py
from django.conf.urls import url

from .views import RegisterView, LoginView, AccountView, UserList, SearchUser, \
    LogoutView, UserEditView

urlpatterns = [
    # login
    url(
        r'^\/login$',
        LoginView.as_view(),
        name='login'
    ),

    # logout
    url(
        r'^\/logout$',
        LogoutView.as_view(),
        name='logout'
    ),

    # sign up
    url(
        r'^\/signup$',
        RegisterView.as_view(),
        name='signup'
    ),

    # user account
    url(
        r'^\/(?P<pk>\d+)$',
        AccountView.as_view(),
        name='account'
    ),

    # user list
    url(
        r'^$',
        UserList.as_view(),
        name='list'
    ),

    # search user
    url(
        r'^\/search/(?P<first_name>.*)/$',
        SearchUser.as_view(),
        name='search-user'
    ),

    # edit user
    url(
        r'^\/(?P<pk>\d+)/edit$',
       UserEditView.as_view(),

        name='edit-user'
    ),


]

simple/users/models.py
from __future__ import unicode_literals

from .abstract_models import AbstractUser, AbstractUserLog


class User(AbstractUser):
    pass


class UserLog(AbstractUserLog):
    pass

simple/users/forms.py
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django import forms

from users.constants import UserRoles
from .models import User


class UserCreationAdminForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required
    fields, plus a repeated password.
    """
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation',
                                widget=forms.PasswordInput)
    role = forms.ChoiceField(choices=UserRoles.USER_ROLES)

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'birthday', 'country',
                  'city', 'occupation', 'password1', 'password2', 'role',
                  'avatar')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeAdminForm(forms.ModelForm):
    """
    A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()
    role = forms.ChoiceField(choices=UserRoles.USER_ROLES)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'birthday', 'country',
                  'city', 'occupation', 'about_me', 'role', 'avatar',)
        readonly_fields = ('email', 'date_joined', 'last_login',)

    def clean_password(self):
        return self.initial["password"]


class UserCreationForm(forms.ModelForm):
    """
    A form for creating new users.
    """
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'birthday', 'country',
                  'city', 'occupation', 'about_me', 'password1', 'password2', 'avatar')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """
    A form for updating users.
    """

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'birthday', 'country',
                  'city', 'occupation', 'about_me', 'avatar',)
        readonly_fields = ('date_joined', 'last_login',)

simple/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.views.generic import DetailView, ListView
from django.views.generic.base import TemplateView, RedirectView
from django.views.generic.edit import CreateView, UpdateView
from django.core.urlresolvers import reverse

from core.utils import WordFilter
from forms import UserCreationForm, UserChangeForm
from users.mixins import NotLoginRequiredMixin
from users.models import User


class LoginView(NotLoginRequiredMixin, TemplateView):
    """
    Login View, custom form handling related with a custom .html template
    Fields are email and password, both gathered by POST.
    Errors list like {{ errors }}
    """
    template_name = 'users/login.html'
    success_url = '/'

    def __init__(self, **kwargs):
        super(LoginView, self).__init__(**kwargs)
        self.errors = []

    def get(self, request, *args, **kwargs):
        return super(LoginView, self).get(request, args, kwargs)

    def post(self, request, **kwargs):
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(email=email, password=password)
        if user is None:
            self.errors.append('Credentials are invalid')
        else:
            login(request, user)
            return redirect('/')
        return super(LoginView, self).get(request, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        context['errors'] = self.errors
        return context


class LogoutView(RedirectView):
    """
    Logout will logout and redirect to login view, regardless of the user having
    been logged in.
    """
    pattern_name = 'users:login'

    def get_redirect_url(self, *args, **kwargs):
        logout(self.request)
        return super(LogoutView, self).get_redirect_url(*args, **kwargs)


class RegisterView(NotLoginRequiredMixin, CreateView):
    template_name = 'users/register.html'
    form_class = UserCreationForm
    success_url = '/'


class AccountView(DetailView):
    template_name = 'users/account.html'
    model = User
    context_object_name = 'context_user'


class UserList(ListView):
    """
    Display user's lists.
    Everybody can see all users.
    """
    model = User
    template_name = 'users/list.html'
    context_object_name = 'users'


class SearchUser(ListView):
    """
    Display user search.
    If an user input the user's firstname, it shows users with this name.
    Else if, it shows No Results
    """
    model = User
    context_object_name = 'users'
    template_name = 'users/list.html'

    def get_queryset(self):
        filter = self.kwargs['first_name']
        search = self.model.objects.filter(first_name__icontains=filter)
        return search


class UserEditView(UpdateView):
    # TODO not edit user
    model = User
    context_object_name = 'user'
    template_name = 'users/edit.html'
    form_class = UserChangeForm

    def form_valid(self, form):
        form.instance.first_name = WordFilter().clean(form.instance.first_name)
        form.instance.last_name = WordFilter().clean(form.instance.last_name)
        form.instance.country = WordFilter().clean(form.instance.country)
        form.instance.city = WordFilter().clean(form.instance.city)
        form.instance.about_me = WordFilter().clean(form.instance.about_me)
        form.instance.occupation = WordFilter().clean(form.instance.occupation)
        return super(UserEditView, self).form_valid(form)

    def get_success_url(self):
        return reverse('users:account', args=[self.kwargs['pk']])

simple/templates/users/account.html
{% extends "users/base.html" %}
{% load static %}
{% load breadcrumb %}

{% block breadcrumb_ %}
    {{ block.super }}
    {% with "User '"|add:context_user.get_short_name|add:"'" as user_name %}
        {% breadcrumb_url user_name "users:account" context_user.id %}
    {% endwith %}
{% endblock %}

{% block menu_title %}
    <h1>{{ context_user.get_full_name }}</h1>
{% endblock %}

{% block app_content %}
    <div class="account-panels">
        <h2 id="personal">Personal</h2>
        <div>
            <div class="row">
                <div class="col-md-4">
                    <a href="{{ MEDIA_URL }}{{context_user.avatar }}" onclick="window.open(this.href,'resizable=yes,location=yes,toolbar=no,status=no,fullscreen=yes,dependent=no,status');return false">
                    <img class="profile-picture" src="{{ MEDIA_URL }}{{context_user.avatar }}" /></a>
                </div>
                <div class="col-md-4">
                    <div class="row">
                        {{ context_user.occupation }}
                    </div>
                    <div class="row">
                        {{ context_user.city }}, {{ context_user.country }}
                    </div>
                    <div>
                        {% if request.user.id == context_user.id %}
                            {{ context_user.birthday }}
                        {% endif %}
                    </div>
                    <div class="row">
                        {{ context_user.get_role_str }}
                        {% if context_user.is_staff %}
                            (Staff)
                        {% endif %}
                    </div>
                    <div class="row">
                        {% if request.user.id == context_user.id %}
                            {{ context_user.email }}
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="row">
                        Member since {{ context_user.date_joined }}
                    </div>
                    <div class="row">
                        Last seen {{ context_user.last_login }}
                    </div>
                    <div class="row">
                        X profile views
                    </div>
                </div>
            </div>
        </div>

        <h2 id="stats">Stats</h2>
        <div>
            <i>Coming soon...</i>
        </div>

        <h2 id="about-me">About me</h2>
        <div>
            <i>{{ context_user.about_me }}</i>
        </div>
    </div>

{% endblock %}

simple/templates/users/base.html
{% extends "base.html" %}
{% load breadcrumb %}

{% block breadcrumb_ %}
    {{ block.super }}
    {% breadcrumb_url "Users" "users:list" %}
{% endblock %}

{% block content_ %}
    {% include "users/left-sidebar.html" with selection="account" %}
    {% block app_content %}
    {% endblock %}
{% endblock %}

simple/templates/users/edit.html
{% extends "projects/base.html" %}
{% load breadcrumb %}

{% block breadcrumb_ %}
    {{ block.super }}
    {% with "User '"|add:user.get_short_name|add:"'" as user_name %}
        {% breadcrumb_url user_name "users:account" user.id %}
    {% endwith %}
    {% breadcrumb_url "Edit user" "users:edit-user" user.id %}
{% endblock %}

{% block menu_title %}
    <h1>Edit user</h1>
{% endblock %}

{% block app_content %}
    <div class="center box" style="width:400px">
        <form method="post" enctype="multipart/form-data" action="">
            {# TODO 2 columns on large displays #}
            <div class="row">
                <div class="form-label">
                    <label for="id_email">Email:</label>
                </div>
                {{ user.email }}
            </div>
            {% include "form.html" with required_mark="*" %}
            <input type="submit" value="Edit"/>
        </form>
    </div>
{% endblock %}

simple/templates/users/left-sidebar.html
<div class="left-sidebar">
    <ul>
        <li class="{% if selection == "account" %}selected{% endif %}">
            <a href="{% url "users:account" context_user.id %}">View profile</a>
        </li>
        {% if selection == "account" %}
            <li>
                <ul>
                    <li><a href="#personal">Personal</a></li>
                    <li><a href="#stats">Stats</a></li>
                    <li><a href="#about-me">About me</a></li>
                </ul>
            </li>
        {% endif %}

        <li class="{% if selection == "edit-account" %}selected{% endif %}">
            <a href="{% url "users:edit-user" context_user.id %}">Edit profile</a>
        </li>

        <li class="{% if selection == "user-projects" %}selected{% endif %}">
            <a href="{% url "projects:user-list" context_user.id %}">
                {% if context_user == request.user %}
                    My projects
                {% else %}
                    {{ context_user.get_short_name }} projects
                {% endif %}
            </a>
        </li>

        <li class="{% if selection == "contributing-to" %}selected{% endif %}">
            <a href="#">Contributing to</a>
        </li>
        {% if selection == "contributing-to" %}
            <li>
                <ul>
                    <li><a href="#">Membership</a></li>
                </ul>
            </li>
        {% endif %}

        <li class="{% if selection == "favorites" %}selected{% endif %}">
            <a href="{% url "projects:favorites" %}">My favorites</a>
        </li>

        <li class="{% if selection == "approve-contributors" %}selected{% endif %}">
            <a href="{% url "projects:approve-contributions-list" %}">Approve contributors</a>
        </li>

        <li class="{% if selection == "approve-projects" %}selected{% endif %}">
            <a href="{% url "projects:approve-list" %}">Approve projects</a>
        </li>

        <li><a href="{% url "users:logout" %}">Log Out</a></li>
    </ul>
</div>

simple/templates/users/list.html
{% extends "users/base.html" %}
{% load staticfiles %}

{% block menu_title %}
    <h1>Users</h1>
{% endblock %}

{% block content_ %}

    <script type="text/javascript">
        function search(event, user) {
            if (event.which == 13 || event.keyCode == 13){
                location.href= '/users/search/' + user;
            }
        }
    </script>

    <div class="row search">
        <div class="input-group">
            <span class="input-group-addon">
                <i class="glyphicon glyphicon-search"></i>
            </span>
            <input id="txtSearch" type="text" class="form-control" placeholder="Search for name..." onkeypress="if(this.value)search(event,this.value)"/>
        </div>
    </div>

    <ul class="user-list">
        {% for user in users %}


                    <div class="col-xs-6 col-md-3">
                        <div class="thumbnail" style="min-height:200px;">
                         <a href="/users/{{ user.id }}"><img style="width:150px" class="imgCustom" src="media/{{ user.avatar }}" alt="..."></a>
                          <div class="caption">
                            <h3>Hi, I'm {{ user.first_name }} {{ user.last_name }}</h3>
                            <p> My birthday is: {{  user.birthday }}</p>
                            <p>    I'm from: {{ user.city }}</p>
                          </div>
                        </div>
                    </div>


            {% empty %}
                 <div class='alert alert-info alert-dismissible error-search' role= 'alert'>
                        <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hideen='true'>&times;</span></button>
                        <strong>No results</strong> Your search returned no matches.
                 </div>
        {% endfor %}

    </ul>


{% endblock %}

simple/templates/users/login.html
{% extends "users/base.html" %}
{% load breadcrumb %}

{% block breadcrumb_ %}
    {{ block.super }}
    {% breadcrumb_url "Log in" "users:login" %}
{% endblock %}

{% block menu_title %}
    <h1>Log in</h1>
{% endblock %}

{% block content_ %}
    <div class="center box" style="width:400px">
        <form method="post" action="">
            {% for error in errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
            {% csrf_token %}
            <input type="text" name="email" placeholder="Email" />
            <input type="password" name="password" placeholder="Password" />
            <input type="submit" value="Login" />
            <input type="hidden" name="next" value="{{ next }}" />
        </form>
    </div>
{% endblock %}

simple/templates/users/register.html
{% extends "users/base.html" %}
{% load breadcrumb %}

{% block breadcrumb_ %}
    {{ block.super }}
    {% breadcrumb_url "Sign up" "users:signup" %}
{% endblock %}

{% block menu_title %}
    <h1>Sign up</h1>
{% endblock %}

{% block content_ %}
    <div class="center box" style="width:500px">
        <form method="post" enctype="multipart/form-data" action="">
            {% include "form.html" with required_mark="*" %}
            <input type="submit" value="Register" />
        </form>
    </div>
{% endblock %}