simple/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users', include('users.urls', namespace='users')),
    url(r'^projects', include('projects.urls', namespace='projects')),
    url(r'^', include('home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simple/home/urls.py
from django.conf.urls import url

from home.views import LandingView

urlpatterns = [
    # Landing page
    url('^$', LandingView.as_view(), name='landing'),
]

simple/projects/urls.py
from django.conf.urls import url, include
from views import ProjectEdit
from forms import ProjectQuestionForm
from views import revokeproject, favorite_create, favorite_delete
from .views import ProjectDetail, ProjectList, ProjectNewView,\
    ProjectApproveList, ProjectApproveView, ProjectDenyView, \
    ProjectContributeView, ProjectPendingApproval, \
    ProjectApproveContributionList, UserProjectList, \
    ProjectContributionApproveView, ProjectContributionDenyView,\
    SearchProject, UpvoteView, DownvoteView, ProjectTechnicalRequestList, \
    ProjectTechnicalRequestNewView, FavoritesView,ProjectTechnicalRequestAnswerDetail, ProjectTechnicalRequestAnswerNewView, NotificationsView

urlpatterns = [
    # Include comments application
    url(
        r'^\/(?P<project>\d+)/comments',
        include('projects.comments.urls', namespace='comments')
    ),

    # Include activities application
    url(
       r'^\/(?P<project>\d+)/activities',
       include('projects.activities.urls', namespace='activities')
    ),

    # List of Projects
    url(
        r'^$',
        ProjectList.as_view(),
        name='list'
    ),

    # List of Projects by User
    url(
        r'^\/user/(?P<user>\d+)$',
        UserProjectList.as_view(),
        name='user-list'
    ),


    # Project details
    url(
        r'^\/(?P<pk>\d+)$',
        ProjectDetail.as_view(),
        name='detail'
    ),

    # New project
    url(
        r'^\/new$',
        ProjectNewView.as_view(),
        name='new'
    ),

    # Search Project
    url(
        r'^\/search/(?P<title>.*)/$',
        SearchProject.as_view(),
        name='search-project'
    ),

    # Pending approval message view shown after project creation
    url(
        r'^\/pending-approval',
        ProjectPendingApproval.as_view(),
        name='pending-approval'
    ),

    # Approve / deny projects list
    url(
        r'^\/approve$',
        ProjectApproveList.as_view(),
        name='approve-list'
    ),

    # Approve project
    url(
        r'^\/approve/(?P<pk>\d+)$',
        ProjectApproveView.as_view(),
        name='approve-project'
    ),

    # Deny project
    url(
        r'^\/deny/(?P<pk>\d+)$',
        ProjectDenyView.as_view(),
        name='deny-project'
    ),

    # Contribute to project
    url(
        r'\/(?P<pk>\d+)/contribute$',
        ProjectContributeView.as_view(),
        name='contribute'
    ),

    # Approve / deny contribution list
    url(
        r'\/approve-contributions$',
        ProjectApproveContributionList.as_view(),
        name='approve-contributions-list'
    ),

    # Approve contribution
    url(
        r'\/approve-contribution/project/(?P<pk>\d+)/user/(?P<user>\d+)/$',
        ProjectContributionApproveView.as_view(),
        name='approve-contribution'
    ),

    # Deny contribution
    url(
        r'\/deny-contribution/project/(?P<pk>\d+)/user/(?P<user>\d+)$',
        ProjectContributionDenyView.as_view(),
        name='deny-contribution'
    ),

    # Edit Project
    url(
        r'^\/(?P<pk>\d+)/edit$',
        ProjectEdit.as_view(),
        name='edit'
    ),

    # Technical Requests list
    url(
        r'^\/(?P<project>\d+)/technical-requests$',
        ProjectTechnicalRequestList.as_view(),
        name='technical-requests'
    ),

    # Add Technical Request
    url(
        r'^\/(?P<project>\d+)/technical-requests/new$',
        ProjectTechnicalRequestNewView.as_view(),
        name='technical-request-new'
    ),

    # See Technical Request Answer
    url(
        r'^\/(?P<project>\d+)/technical-requests/(?P<pk>\d+)$',
        ProjectTechnicalRequestAnswerDetail.as_view(),
        name='technical-request-answer'
    ),

    # Reply Technical Request
    url(
        r'^\/(?P<project>\d+)/technical-requests/(?P<pk>\d+)/reply',
        ProjectTechnicalRequestAnswerNewView.as_view(),
        name='technical-request-answer-new'
    ),


    # Vote up project
    url(
        r'^\/(?P<pk>\d+)/vote/up$',
        UpvoteView.as_view(),
        name='upvote'
    ),

    # Vote down project
    url(
        r'^\/(?P<pk>\d+)/vote/down$',
        DownvoteView.as_view(),
        name='downvote'
    ),

    # Favorites projects
    url(
        r'^\/favorites$',
        FavoritesView.as_view(),
        name='favorites'
    ),

    # New favorite
    url(
        r'^\/favorites/create$',
        favorite_create,
        name='favorite_create'
    ),

    # Delete favorite
    url(
        r'^\/favorites/delete$',
        favorite_delete,
        name='favorite_delete'
    ),

    url(
        r'^\/(?P<pk>\d+)/notifications$',
        NotificationsView.as_view(),
        name='notifications'
    ),
    # Revoke in a project
    url(r'\/contribute/delete$',
        revokeproject,
        name='revoke'
        )

]

simple/users/urls.py
from django.conf.urls import url

from .views import RegisterView, LoginView, AccountView, UserList, SearchUser, \
    LogoutView, UserEditView

urlpatterns = [
    # login
    url(
        r'^\/login$',
        LoginView.as_view(),
        name='login'
    ),

    # logout
    url(
        r'^\/logout$',
        LogoutView.as_view(),
        name='logout'
    ),

    # sign up
    url(
        r'^\/signup$',
        RegisterView.as_view(),
        name='signup'
    ),

    # user account
    url(
        r'^\/(?P<pk>\d+)$',
        AccountView.as_view(),
        name='account'
    ),

    # user list
    url(
        r'^$',
        UserList.as_view(),
        name='list'
    ),

    # search user
    url(
        r'^\/search/(?P<first_name>.*)/$',
        SearchUser.as_view(),
        name='search-user'
    ),

    # edit user
    url(
        r'^\/(?P<pk>\d+)/edit$',
       UserEditView.as_view(),

        name='edit-user'
    ),


]

simple/templates/attachments.html
{% load file %}

{% for attachment in attachments %}
    <span class="attachment">
        <i class="fa fa-paperclip fa-2" aria-hidden="true"></i>
        <a href="{{ attachment.object.url }}" target="_blank">
            {{ attachment.object|filename }}
        </a>
        <span class="attachment-meta">{{ attachment.object.size|filesize }}</span>
    </span>
{% endfor %}

simple/templates/base.html
{% load compress %}
{% load static %}
{% load breadcrumb %}
<html>
<head>
    <link rel="icon" href="{% static "img/favicon.png" %}">
    <title>Simple - The project sharing platform</title>

    {% block cdn_stylesheets %}
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    {% endblock %}

    {% block stylesheets %}
        {% compress css %}
            <link rel="stylesheet" type="text/scss" href="{% static "scss/style.scss" %}" />
        {% endcompress %}
    {% endblock %}
</head>
<body>
    {% block header %}
        <header>
            <div id="header-top">
                {% block header_ %}
                    <a id="logo" href="{% url "projects:list" %}">{{ PROJECT_NAME }}</a>

                    {# header navigation #}
                    {% block header-nav %}
                        <nav id="header-nav">
                        {% block header-nav_ %}
                            {% include "header-nav.html" %}
                        {% endblock %}
                        </nav>
                    {% endblock %}
                {% endblock %}
            </div>
            {% block breadcrumb %}
                <div id="breadcrumb">
                    {% block breadcrumb_ %}
                        {# home case exception - do others with breadcrumb or breadcrumb_url #}
                        <a href="{% url "projects:list" %}">
                            <i class="fa fa-home fa-2" aria-hidden="true"></i>
                        </a>
                    {% endblock %}
                </div>
            {% endblock %}
        </header>
    {% endblock %}

    {% block menu %}
        <nav id="menu">
        {% block menu_ %}
            <div id="menu-title">{% block menu_title %}{% endblock %}</div>
        {% endblock %}
        </nav>
    {% endblock %}

    {% block content %}
        <div id="content">
            {% block content_ %}
            {% endblock %}
        </div>
    {% endblock %}

    {% block footer %}
        <footer>
            <div>
                <img height="20" src="{% static "img/favicon.png" %}" />
            </div>
            <div>
                Copyright &copy; 2016 Simple
            </div>
        </footer>
    {% endblock %}

    {# Scripts #}
    {% block cdn_scripts %}
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        {{ form.media }}
    {% endblock %}

    {% block scripts %}
        <script src="{% static "js/jquery.config.js" %}"></script>
        <script src="{% static "js/general.js" %}"></script>
    {% endblock %}

    {% block local_scripts %}
    {% endblock %}
</body>
</html>

simple/templates/form.html
{% if form.errors %}
    <div class="error">
        {{ form.non_field_errors }}
        {% for field in form %}
            {% if field.errors %}
                {{ field.label_tag }} {{ field.errors }}
            {% endif %}
        {% endfor %}
    </div>
{% endif %}
{% csrf_token %}
{% for field in form %}
    <div class="row">
        {% if not field.is_hidden %}
            <div class="form-label">
                {{ field.label_tag }}
                {% if field.field.required %}
                    {{ required_mark }}
                {% endif %}
            </div>
        {% endif %}
        {{ field }}
    </div>
{% endfor %}
<input type="hidden" name="next" value="{{ next }}" />

simple/templates/form_delete.html
{% csrf_token %}
<p>Are you sure you want to delete {{ object }}?</p>
<input type="submit" value="Delete" />

simple/templates/header-nav.html
<ul>
    <li><a href="{% url "projects:list" %}">Projects</a></li>
    <li><a href="{% url "users:list" %}">Users</a></li>
    {% if request.user.is_authenticated %}
        <li><a href="{% url "projects:notifications" request.user.id %}">Notifications (0)</a></li>
        <li><a href="{% url "users:account" request.user.id %}">{{ request.user.first_name }}</a></li>
        <li><a href="javascript:void(document.body.style.fontSize='20Px')"><span class="glyphicon glyphicon-zoom-in"></span></a> </li>
        <li><a href="javascript:void(document.body.style.fontSize='16Px')"><span class="glyphicon glyphicon-zoom-out"></span></a> </li>
    {% else %}
        <li><a href="{% url "users:login" %}">Log In</a></li>
        <li><a href="{% url "users:signup" %}">Sign Up</a></li>
    {% endif %}

</ul>